import { vocabularyImageUrls } from './image-manifest.generated';
import { EnglishVocabularyItem, VocabularyPartOfSpeech, VocabularyTopicId } from './types';

type VocabularyRow = readonly [
  word: string,
  pronunciation: string,
  partOfSpeech: VocabularyPartOfSpeech,
  vietnameseMeaning: string,
  example: string,
  exampleTranslation: string,
  topicId: VocabularyTopicId,
];

const rows: VocabularyRow[] = [
  ['go', '/ɡəʊ/', 'verb', 'đi', 'I go to school every day.', 'Tôi đi học mỗi ngày.', 'actions'],
  ['come', '/kʌm/', 'verb', 'đến', 'Please come here.', 'Hãy đến đây.', 'actions'],
  ['eat', '/iːt/', 'verb', 'ăn', 'We eat dinner at seven.', 'Chúng tôi ăn tối lúc bảy giờ.', 'actions'],
  ['drink', '/drɪŋk/', 'verb', 'uống', 'She drinks a glass of water.', 'Cô ấy uống một ly nước.', 'actions'],
  ['sleep', '/sliːp/', 'verb', 'ngủ', 'The baby is sleeping.', 'Em bé đang ngủ.', 'actions'],
  ['wake', '/weɪk/', 'verb', 'thức dậy', 'I wake up at six.', 'Tôi thức dậy lúc sáu giờ.', 'actions'],
  ['work', '/wɜːk/', 'verb', 'làm việc', 'My parents work at home.', 'Bố mẹ tôi làm việc tại nhà.', 'actions'],
  ['study', '/ˈstʌdi/', 'verb', 'học', 'They study English together.', 'Họ học tiếng Anh cùng nhau.', 'actions'],
  ['read', '/riːd/', 'verb', 'đọc', 'He reads a book before bed.', 'Anh ấy đọc sách trước khi ngủ.', 'actions'],
  ['write', '/raɪt/', 'verb', 'viết', 'Write your name here.', 'Hãy viết tên của bạn ở đây.', 'actions'],

  ['family', '/ˈfæməli/', 'noun', 'gia đình', 'My family lives in Vietnam.', 'Gia đình tôi sống ở Việt Nam.', 'people'],
  ['mother', '/ˈmʌðə/', 'noun', 'mẹ', 'My mother is a teacher.', 'Mẹ tôi là giáo viên.', 'people'],
  ['father', '/ˈfɑːðə/', 'noun', 'bố', 'Her father drives a bus.', 'Bố cô ấy lái xe buýt.', 'people'],
  ['parent', '/ˈpeərənt/', 'noun', 'phụ huynh', 'Every parent wants the best for their child.', 'Mỗi phụ huynh đều muốn điều tốt nhất cho con.', 'people'],
  ['child', '/tʃaɪld/', 'noun', 'đứa trẻ', 'The child is playing outside.', 'Đứa trẻ đang chơi bên ngoài.', 'people'],
  ['friend', '/frend/', 'noun', 'bạn bè', 'Lan is my best friend.', 'Lan là bạn thân nhất của tôi.', 'people'],
  ['man', '/mæn/', 'noun', 'người đàn ông', 'The man is wearing a blue shirt.', 'Người đàn ông đang mặc áo xanh.', 'people'],
  ['woman', '/ˈwʊmən/', 'noun', 'người phụ nữ', 'That woman is a doctor.', 'Người phụ nữ đó là bác sĩ.', 'people'],
  ['people', '/ˈpiːpəl/', 'noun', 'mọi người', 'Many people are in the park.', 'Có nhiều người trong công viên.', 'people'],
  ['baby', '/ˈbeɪbi/', 'noun', 'em bé', 'The baby has small hands.', 'Em bé có đôi tay nhỏ.', 'people'],

  ['house', '/haʊs/', 'noun', 'ngôi nhà', 'Their house has a red roof.', 'Ngôi nhà của họ có mái đỏ.', 'home'],
  ['room', '/ruːm/', 'noun', 'căn phòng', 'My room is clean and bright.', 'Phòng của tôi sạch sẽ và sáng sủa.', 'home'],
  ['door', '/dɔː/', 'noun', 'cánh cửa', 'Please close the door.', 'Vui lòng đóng cửa.', 'home'],
  ['window', '/ˈwɪndəʊ/', 'noun', 'cửa sổ', 'Open the window for some fresh air.', 'Mở cửa sổ để đón không khí trong lành.', 'home'],
  ['table', '/ˈteɪbəl/', 'noun', 'cái bàn', 'The keys are on the table.', 'Chìa khóa ở trên bàn.', 'home'],
  ['chair', '/tʃeə/', 'noun', 'cái ghế', 'Sit on this chair.', 'Hãy ngồi trên chiếc ghế này.', 'home'],
  ['bed', '/bed/', 'noun', 'cái giường', 'The cat is under the bed.', 'Con mèo ở dưới giường.', 'home'],
  ['kitchen', '/ˈkɪtʃɪn/', 'noun', 'nhà bếp', 'She is cooking in the kitchen.', 'Cô ấy đang nấu ăn trong bếp.', 'home'],
  ['bathroom', '/ˈbɑːθruːm/', 'noun', 'phòng tắm', 'The bathroom is next to my room.', 'Phòng tắm ở cạnh phòng tôi.', 'home'],
  ['key', '/kiː/', 'noun', 'chìa khóa', 'I cannot find my key.', 'Tôi không thể tìm thấy chìa khóa.', 'home'],

  ['food', '/fuːd/', 'noun', 'thức ăn', 'This food tastes good.', 'Món ăn này có vị ngon.', 'food'],
  ['water', '/ˈwɔːtə/', 'noun', 'nước', 'Drink more water every day.', 'Hãy uống nhiều nước hơn mỗi ngày.', 'food'],
  ['rice', '/raɪs/', 'noun', 'cơm; gạo', 'We usually eat rice for lunch.', 'Chúng tôi thường ăn cơm vào bữa trưa.', 'food'],
  ['bread', '/bred/', 'noun', 'bánh mì', 'I bought some fresh bread.', 'Tôi đã mua một ít bánh mì tươi.', 'food'],
  ['milk', '/mɪlk/', 'noun', 'sữa', 'The child drinks milk in the morning.', 'Đứa trẻ uống sữa vào buổi sáng.', 'food'],
  ['coffee', '/ˈkɒfi/', 'noun', 'cà phê', 'My father likes black coffee.', 'Bố tôi thích cà phê đen.', 'food'],
  ['tea', '/tiː/', 'noun', 'trà', 'Would you like some tea?', 'Bạn có muốn uống trà không?', 'food'],
  ['fruit', '/fruːt/', 'noun', 'trái cây', 'Fruit is good for your health.', 'Trái cây tốt cho sức khỏe.', 'food'],
  ['apple', '/ˈæpəl/', 'noun', 'quả táo', 'She eats an apple after lunch.', 'Cô ấy ăn một quả táo sau bữa trưa.', 'food'],
  ['egg', '/eɡ/', 'noun', 'quả trứng', 'There are two eggs in the bowl.', 'Có hai quả trứng trong tô.', 'food'],

  ['dog', '/dɒɡ/', 'noun', 'con chó', 'The dog runs in the garden.', 'Con chó chạy trong vườn.', 'nature'],
  ['cat', '/kæt/', 'noun', 'con mèo', 'Our cat has green eyes.', 'Con mèo của chúng tôi có mắt xanh.', 'nature'],
  ['bird', '/bɜːd/', 'noun', 'con chim', 'A bird is singing in the tree.', 'Một con chim đang hót trên cây.', 'nature'],
  ['fish', '/fɪʃ/', 'noun', 'con cá', 'The fish swims in clear water.', 'Con cá bơi trong làn nước trong.', 'nature'],
  ['horse', '/hɔːs/', 'noun', 'con ngựa', 'The horse is running fast.', 'Con ngựa đang chạy nhanh.', 'nature'],
  ['tree', '/triː/', 'noun', 'cây', 'That tree is very old.', 'Cái cây đó rất lâu năm.', 'nature'],
  ['flower', '/ˈflaʊə/', 'noun', 'bông hoa', 'This flower smells wonderful.', 'Bông hoa này có mùi rất thơm.', 'nature'],
  ['sun', '/sʌn/', 'noun', 'mặt trời', 'The sun rises in the east.', 'Mặt trời mọc ở phía đông.', 'nature'],
  ['rain', '/reɪn/', 'noun', 'mưa', 'The rain stopped this afternoon.', 'Mưa đã tạnh vào chiều nay.', 'nature'],
  ['river', '/ˈrɪvə/', 'noun', 'dòng sông', 'A long river runs through the city.', 'Một dòng sông dài chảy qua thành phố.', 'nature'],

  ['school', '/skuːl/', 'noun', 'trường học', 'The school is near my house.', 'Trường học ở gần nhà tôi.', 'places'],
  ['hospital', '/ˈhɒspɪtəl/', 'noun', 'bệnh viện', 'He works at the city hospital.', 'Anh ấy làm việc tại bệnh viện thành phố.', 'places'],
  ['market', '/ˈmɑːkɪt/', 'noun', 'chợ', 'My mother buys vegetables at the market.', 'Mẹ tôi mua rau ở chợ.', 'places'],
  ['shop', '/ʃɒp/', 'noun', 'cửa hàng', 'That shop sells books.', 'Cửa hàng đó bán sách.', 'places'],
  ['park', '/pɑːk/', 'noun', 'công viên', 'We walk in the park on Sunday.', 'Chúng tôi đi bộ trong công viên vào Chủ nhật.', 'places'],
  ['road', '/rəʊd/', 'noun', 'con đường', 'This road leads to the beach.', 'Con đường này dẫn đến bãi biển.', 'places'],
  ['city', '/ˈsɪti/', 'noun', 'thành phố', 'Ho Chi Minh City is very busy.', 'Thành phố Hồ Chí Minh rất nhộn nhịp.', 'places'],
  ['country', '/ˈkʌntri/', 'noun', 'đất nước', 'Vietnam is a beautiful country.', 'Việt Nam là một đất nước xinh đẹp.', 'places'],
  ['airport', '/ˈeəpɔːt/', 'noun', 'sân bay', 'We arrived at the airport early.', 'Chúng tôi đến sân bay sớm.', 'places'],
  ['station', '/ˈsteɪʃən/', 'noun', 'nhà ga; trạm', 'The train station is on the left.', 'Nhà ga ở bên trái.', 'places'],

  ['day', '/deɪ/', 'noun', 'ngày', 'It was a beautiful day.', 'Đó là một ngày đẹp trời.', 'time'],
  ['week', '/wiːk/', 'noun', 'tuần', 'I exercise three times a week.', 'Tôi tập thể dục ba lần một tuần.', 'time'],
  ['month', '/mʌnθ/', 'noun', 'tháng', 'Next month is my birthday.', 'Tháng sau là sinh nhật tôi.', 'time'],
  ['year', '/jɪə/', 'noun', 'năm', 'She visits her family every year.', 'Cô ấy thăm gia đình mỗi năm.', 'time'],
  ['today', '/təˈdeɪ/', 'adverb', 'hôm nay', 'I am busy today.', 'Hôm nay tôi bận.', 'time'],
  ['tomorrow', '/təˈmɒrəʊ/', 'adverb', 'ngày mai', 'We will meet tomorrow.', 'Chúng ta sẽ gặp nhau vào ngày mai.', 'time'],
  ['morning', '/ˈmɔːnɪŋ/', 'noun', 'buổi sáng', 'The air is cool in the morning.', 'Không khí mát mẻ vào buổi sáng.', 'time'],
  ['afternoon', '/ˌɑːftəˈnuːn/', 'noun', 'buổi chiều', 'See you this afternoon.', 'Hẹn gặp bạn chiều nay.', 'time'],
  ['evening', '/ˈiːvnɪŋ/', 'noun', 'buổi tối', 'We watch television in the evening.', 'Chúng tôi xem tivi vào buổi tối.', 'time'],
  ['night', '/naɪt/', 'noun', 'ban đêm', 'The stars are bright tonight.', 'Các vì sao sáng vào tối nay.', 'time'],

  ['good', '/ɡʊd/', 'adjective', 'tốt', 'You did a good job.', 'Bạn đã làm rất tốt.', 'descriptions'],
  ['bad', '/bæd/', 'adjective', 'xấu; tệ', 'The weather is bad today.', 'Thời tiết hôm nay rất xấu.', 'descriptions'],
  ['big', '/bɪɡ/', 'adjective', 'to; lớn', 'They live in a big house.', 'Họ sống trong một ngôi nhà lớn.', 'descriptions'],
  ['small', '/smɔːl/', 'adjective', 'nhỏ', 'I need a small bag.', 'Tôi cần một chiếc túi nhỏ.', 'descriptions'],
  ['new', '/njuː/', 'adjective', 'mới', 'This is my new phone.', 'Đây là điện thoại mới của tôi.', 'descriptions'],
  ['old', '/əʊld/', 'adjective', 'cũ; già', 'That is an old building.', 'Đó là một tòa nhà cũ.', 'descriptions'],
  ['happy', '/ˈhæpi/', 'adjective', 'vui vẻ', 'The children look happy.', 'Những đứa trẻ trông vui vẻ.', 'descriptions'],
  ['sad', '/sæd/', 'adjective', 'buồn', 'Why are you sad?', 'Tại sao bạn buồn?', 'descriptions'],
  ['hot', '/hɒt/', 'adjective', 'nóng', 'The soup is still hot.', 'Món súp vẫn còn nóng.', 'descriptions'],
  ['cold', '/kəʊld/', 'adjective', 'lạnh', 'It is cold outside.', 'Bên ngoài trời lạnh.', 'descriptions'],

  ['have', '/hæv/', 'verb', 'có', 'I have two brothers.', 'Tôi có hai anh em trai.', 'common-verbs'],
  ['make', '/meɪk/', 'verb', 'làm; tạo ra', 'We make breakfast together.', 'Chúng tôi cùng nhau làm bữa sáng.', 'common-verbs'],
  ['take', '/teɪk/', 'verb', 'lấy; mang', 'Take an umbrella with you.', 'Hãy mang theo một chiếc ô.', 'common-verbs'],
  ['give', '/ɡɪv/', 'verb', 'đưa; cho', 'Please give me the book.', 'Vui lòng đưa tôi cuốn sách.', 'common-verbs'],
  ['get', '/ɡet/', 'verb', 'nhận; có được', 'I get many emails every day.', 'Tôi nhận nhiều email mỗi ngày.', 'common-verbs'],
  ['know', '/nəʊ/', 'verb', 'biết', 'Do you know her name?', 'Bạn có biết tên cô ấy không?', 'common-verbs'],
  ['think', '/θɪŋk/', 'verb', 'suy nghĩ', 'I think this answer is right.', 'Tôi nghĩ câu trả lời này đúng.', 'common-verbs'],
  ['want', '/wɒnt/', 'verb', 'muốn', 'They want a new car.', 'Họ muốn một chiếc xe mới.', 'common-verbs'],
  ['need', '/niːd/', 'verb', 'cần', 'We need more time.', 'Chúng tôi cần thêm thời gian.', 'common-verbs'],
  ['like', '/laɪk/', 'verb', 'thích', 'I like Vietnamese food.', 'Tôi thích đồ ăn Việt Nam.', 'common-verbs'],

  ['say', '/seɪ/', 'verb', 'nói', 'She says hello to everyone.', 'Cô ấy chào mọi người.', 'communication'],
  ['tell', '/tel/', 'verb', 'kể; bảo', 'Tell me your story.', 'Hãy kể cho tôi câu chuyện của bạn.', 'communication'],
  ['speak', '/spiːk/', 'verb', 'nói; phát biểu', 'Can you speak English?', 'Bạn có thể nói tiếng Anh không?', 'communication'],
  ['ask', '/ɑːsk/', 'verb', 'hỏi', 'I want to ask a question.', 'Tôi muốn hỏi một câu.', 'communication'],
  ['answer', '/ˈɑːnsə/', 'verb', 'trả lời', 'Please answer the phone.', 'Vui lòng nghe điện thoại.', 'communication'],
  ['listen', '/ˈlɪsən/', 'verb', 'lắng nghe', 'Listen carefully to the teacher.', 'Hãy chăm chú nghe giáo viên.', 'communication'],
  ['hear', '/hɪə/', 'verb', 'nghe thấy', 'I can hear music upstairs.', 'Tôi có thể nghe thấy nhạc ở tầng trên.', 'communication'],
  ['see', '/siː/', 'verb', 'nhìn thấy', 'I can see the mountains from here.', 'Tôi có thể nhìn thấy núi từ đây.', 'communication'],
  ['look', '/lʊk/', 'verb', 'nhìn', 'Look at this picture.', 'Hãy nhìn vào bức tranh này.', 'communication'],
  ['help', '/help/', 'verb', 'giúp đỡ', 'Could you help me, please?', 'Bạn có thể giúp tôi được không?', 'communication'],

  ['head', '/hed/', 'noun', 'đầu', 'My head hurts today.', 'Hôm nay tôi bị đau đầu.', 'body'],
  ['face', '/feɪs/', 'noun', 'khuôn mặt', 'Wash your face with clean water.', 'Hãy rửa mặt bằng nước sạch.', 'body'],
  ['eye', '/aɪ/', 'noun', 'mắt', 'She has brown eyes.', 'Cô ấy có đôi mắt nâu.', 'body'],
  ['ear', '/ɪə/', 'noun', 'tai', 'The dog has long ears.', 'Con chó có đôi tai dài.', 'body'],
  ['nose', '/nəʊz/', 'noun', 'mũi', 'His nose is cold.', 'Mũi của anh ấy bị lạnh.', 'body'],
  ['mouth', '/maʊθ/', 'noun', 'miệng', 'Open your mouth, please.', 'Vui lòng mở miệng.', 'body'],
  ['hand', '/hænd/', 'noun', 'bàn tay', 'Raise your hand if you know.', 'Hãy giơ tay nếu bạn biết.', 'body'],
  ['arm', '/ɑːm/', 'noun', 'cánh tay', 'He carries the bag under his arm.', 'Anh ấy kẹp chiếc túi dưới cánh tay.', 'body'],
  ['leg', '/leɡ/', 'noun', 'chân', 'She hurt her left leg.', 'Cô ấy bị đau chân trái.', 'body'],
  ['foot', '/fʊt/', 'noun', 'bàn chân', 'My right foot is wet.', 'Bàn chân phải của tôi bị ướt.', 'body'],

  ['shirt', '/ʃɜːt/', 'noun', 'áo sơ mi', 'He is wearing a white shirt.', 'Anh ấy đang mặc áo sơ mi trắng.', 'clothes'],
  ['trousers', '/ˈtraʊzəz/', 'noun', 'quần dài', 'These trousers are too long.', 'Chiếc quần này quá dài.', 'clothes'],
  ['dress', '/dres/', 'noun', 'váy liền', 'She bought a red dress.', 'Cô ấy mua một chiếc váy đỏ.', 'clothes'],
  ['skirt', '/skɜːt/', 'noun', 'chân váy', 'This skirt is very comfortable.', 'Chiếc chân váy này rất thoải mái.', 'clothes'],
  ['shoe', '/ʃuː/', 'noun', 'giày', 'I cannot find my other shoe.', 'Tôi không tìm thấy chiếc giày còn lại.', 'clothes'],
  ['hat', '/hæt/', 'noun', 'mũ', 'Wear a hat in the sun.', 'Hãy đội mũ khi ra nắng.', 'clothes'],
  ['coat', '/kəʊt/', 'noun', 'áo khoác dài', 'Take your coat because it is cold.', 'Hãy mang áo khoác vì trời lạnh.', 'clothes'],
  ['jacket', '/ˈdʒækɪt/', 'noun', 'áo khoác', 'His jacket is on the chair.', 'Áo khoác của anh ấy ở trên ghế.', 'clothes'],
  ['sock', '/sɒk/', 'noun', 'tất', 'There is a blue sock under the bed.', 'Có một chiếc tất xanh dưới giường.', 'clothes'],
  ['bag', '/bæɡ/', 'noun', 'túi', 'My books are in this bag.', 'Sách của tôi ở trong chiếc túi này.', 'clothes'],

  ['car', '/kɑː/', 'noun', 'ô tô', 'Our car is parked outside.', 'Ô tô của chúng tôi đỗ bên ngoài.', 'transport'],
  ['bus', '/bʌs/', 'noun', 'xe buýt', 'I take the bus to work.', 'Tôi đi xe buýt đến chỗ làm.', 'transport'],
  ['train', '/treɪn/', 'noun', 'tàu hỏa', 'The train leaves at nine.', 'Tàu khởi hành lúc chín giờ.', 'transport'],
  ['bicycle', '/ˈbaɪsɪkəl/', 'noun', 'xe đạp', 'She rides her bicycle to school.', 'Cô ấy đi xe đạp đến trường.', 'transport'],
  ['motorbike', '/ˈməʊtəbaɪk/', 'noun', 'xe máy', 'Motorbikes are common in Vietnam.', 'Xe máy rất phổ biến ở Việt Nam.', 'transport'],
  ['boat', '/bəʊt/', 'noun', 'thuyền', 'The small boat crossed the river.', 'Chiếc thuyền nhỏ đã qua sông.', 'transport'],
  ['plane', '/pleɪn/', 'noun', 'máy bay', 'The plane arrived on time.', 'Máy bay đến đúng giờ.', 'transport'],
  ['taxi', '/ˈtæksi/', 'noun', 'taxi', 'We took a taxi to the hotel.', 'Chúng tôi đi taxi đến khách sạn.', 'transport'],
  ['ticket', '/ˈtɪkɪt/', 'noun', 'vé', 'Keep your train ticket safe.', 'Hãy giữ vé tàu cẩn thận.', 'transport'],
  ['journey', '/ˈdʒɜːni/', 'noun', 'hành trình', 'The journey took three hours.', 'Hành trình kéo dài ba giờ.', 'transport'],

  ['teacher', '/ˈtiːtʃə/', 'noun', 'giáo viên', 'Our teacher explains the lesson clearly.', 'Giáo viên giải thích bài học rõ ràng.', 'work-study'],
  ['student', '/ˈstjuːdənt/', 'noun', 'học sinh; sinh viên', 'Every student has a notebook.', 'Mỗi học sinh đều có một quyển vở.', 'work-study'],
  ['office', '/ˈɒfɪs/', 'noun', 'văn phòng', 'Her office is on the second floor.', 'Văn phòng của cô ấy ở tầng hai.', 'work-study'],
  ['computer', '/kəmˈpjuːtə/', 'noun', 'máy tính', 'I use a computer at work.', 'Tôi sử dụng máy tính tại nơi làm việc.', 'work-study'],
  ['lesson', '/ˈlesən/', 'noun', 'bài học', 'Today’s lesson is about travel.', 'Bài học hôm nay nói về du lịch.', 'work-study'],
  ['question', '/ˈkwestʃən/', 'noun', 'câu hỏi', 'The student asked a good question.', 'Học sinh đã hỏi một câu hay.', 'work-study'],
  ['paper', '/ˈpeɪpə/', 'noun', 'giấy', 'Write the answer on the paper.', 'Hãy viết câu trả lời lên giấy.', 'work-study'],
  ['pen', '/pen/', 'noun', 'bút', 'May I borrow your pen?', 'Tôi có thể mượn bút của bạn không?', 'work-study'],
  ['job', '/dʒɒb/', 'noun', 'công việc', 'He found a new job.', 'Anh ấy đã tìm được công việc mới.', 'work-study'],
  ['meeting', '/ˈmiːtɪŋ/', 'noun', 'cuộc họp', 'The meeting starts at ten.', 'Cuộc họp bắt đầu lúc mười giờ.', 'work-study'],

  ['buy', '/baɪ/', 'verb', 'mua', 'I need to buy some vegetables.', 'Tôi cần mua một ít rau.', 'shopping'],
  ['sell', '/sel/', 'verb', 'bán', 'They sell fresh fruit here.', 'Họ bán trái cây tươi ở đây.', 'shopping'],
  ['pay', '/peɪ/', 'verb', 'thanh toán', 'Can I pay by card?', 'Tôi có thể thanh toán bằng thẻ không?', 'shopping'],
  ['price', '/praɪs/', 'noun', 'giá', 'The price is on the label.', 'Giá được ghi trên nhãn.', 'shopping'],
  ['money', '/ˈmʌni/', 'noun', 'tiền', 'I do not have enough money.', 'Tôi không có đủ tiền.', 'shopping'],
  ['cheap', '/tʃiːp/', 'adjective', 'rẻ', 'This shop sells cheap clothes.', 'Cửa hàng này bán quần áo giá rẻ.', 'shopping'],
  ['expensive', '/ɪkˈspensɪv/', 'adjective', 'đắt', 'That restaurant is too expensive.', 'Nhà hàng đó quá đắt.', 'shopping'],
  ['customer', '/ˈkʌstəmə/', 'noun', 'khách hàng', 'The customer asked for help.', 'Khách hàng đã yêu cầu trợ giúp.', 'shopping'],
  ['supermarket', '/ˈsuːpəmɑːkɪt/', 'noun', 'siêu thị', 'The supermarket closes at nine.', 'Siêu thị đóng cửa lúc chín giờ.', 'shopping'],
  ['receipt', '/rɪˈsiːt/', 'noun', 'hóa đơn', 'Please keep your receipt.', 'Vui lòng giữ lại hóa đơn.', 'shopping'],

  ['healthy', '/ˈhelθi/', 'adjective', 'khỏe mạnh', 'Walking is a healthy habit.', 'Đi bộ là một thói quen lành mạnh.', 'health'],
  ['sick', '/sɪk/', 'adjective', 'bị ốm', 'She stayed home because she was sick.', 'Cô ấy ở nhà vì bị ốm.', 'health'],
  ['doctor', '/ˈdɒktə/', 'noun', 'bác sĩ', 'The doctor checked my throat.', 'Bác sĩ đã kiểm tra cổ họng của tôi.', 'health'],
  ['nurse', '/nɜːs/', 'noun', 'y tá', 'The nurse gave him some medicine.', 'Y tá đã đưa thuốc cho anh ấy.', 'health'],
  ['medicine', '/ˈmedɪsən/', 'noun', 'thuốc', 'Take this medicine after food.', 'Hãy uống thuốc này sau khi ăn.', 'health'],
  ['pain', '/peɪn/', 'noun', 'cơn đau', 'I feel a pain in my back.', 'Tôi cảm thấy đau ở lưng.', 'health'],
  ['exercise', '/ˈeksəsaɪz/', 'noun', 'bài tập thể dục', 'Daily exercise keeps you strong.', 'Tập thể dục hằng ngày giúp bạn khỏe mạnh.', 'health'],
  ['rest', '/rest/', 'noun', 'sự nghỉ ngơi', 'You need some rest.', 'Bạn cần nghỉ ngơi.', 'health'],
  ['cough', '/kɒf/', 'noun', 'cơn ho', 'He has a bad cough.', 'Anh ấy bị ho nặng.', 'health'],
  ['fever', '/ˈfiːvə/', 'noun', 'sốt', 'The child has a high fever.', 'Đứa trẻ bị sốt cao.', 'health'],

  ['weather', '/ˈweðə/', 'noun', 'thời tiết', 'The weather is nice today.', 'Thời tiết hôm nay đẹp.', 'weather'],
  ['sunny', '/ˈsʌni/', 'adjective', 'có nắng', 'It will be sunny tomorrow.', 'Ngày mai trời sẽ nắng.', 'weather'],
  ['cloudy', '/ˈklaʊdi/', 'adjective', 'nhiều mây', 'The sky is cloudy this morning.', 'Bầu trời sáng nay nhiều mây.', 'weather'],
  ['windy', '/ˈwɪndi/', 'adjective', 'nhiều gió', 'It is too windy for a picnic.', 'Trời quá nhiều gió để đi dã ngoại.', 'weather'],
  ['storm', '/stɔːm/', 'noun', 'bão', 'The storm damaged several trees.', 'Cơn bão đã làm hư hại vài cây.', 'weather'],
  ['snow', '/snəʊ/', 'noun', 'tuyết', 'The children are playing in the snow.', 'Bọn trẻ đang chơi trong tuyết.', 'weather'],
  ['warm', '/wɔːm/', 'adjective', 'ấm', 'The water is warm enough.', 'Nước đủ ấm.', 'weather'],
  ['cool', '/kuːl/', 'adjective', 'mát', 'The evening air feels cool.', 'Không khí buổi tối mát mẻ.', 'weather'],
  ['dry', '/draɪ/', 'adjective', 'khô', 'Keep your clothes dry.', 'Hãy giữ quần áo khô ráo.', 'weather'],
  ['wet', '/wet/', 'adjective', 'ướt', 'The road is wet after the rain.', 'Con đường bị ướt sau cơn mưa.', 'weather'],

  ['angry', '/ˈæŋɡri/', 'adjective', 'tức giận', 'He was angry about the mistake.', 'Anh ấy tức giận vì lỗi đó.', 'feelings'],
  ['afraid', '/əˈfreɪd/', 'adjective', 'sợ hãi', 'The child is afraid of the dark.', 'Đứa trẻ sợ bóng tối.', 'feelings'],
  ['tired', '/ˈtaɪəd/', 'adjective', 'mệt mỏi', 'I feel tired after work.', 'Tôi cảm thấy mệt sau giờ làm.', 'feelings'],
  ['hungry', '/ˈhʌŋɡri/', 'adjective', 'đói', 'We are hungry after the walk.', 'Chúng tôi đói sau khi đi bộ.', 'feelings'],
  ['thirsty', '/ˈθɜːsti/', 'adjective', 'khát', 'She is thirsty and needs water.', 'Cô ấy khát và cần nước.', 'feelings'],
  ['excited', '/ɪkˈsaɪtɪd/', 'adjective', 'hào hứng', 'They are excited about the trip.', 'Họ hào hứng về chuyến đi.', 'feelings'],
  ['worried', '/ˈwʌrid/', 'adjective', 'lo lắng', 'My mother looks worried.', 'Mẹ tôi trông có vẻ lo lắng.', 'feelings'],
  ['surprised', '/səˈpraɪzd/', 'adjective', 'ngạc nhiên', 'I was surprised by the news.', 'Tôi ngạc nhiên trước tin đó.', 'feelings'],
  ['bored', '/bɔːd/', 'adjective', 'chán', 'The children were bored at home.', 'Bọn trẻ cảm thấy chán khi ở nhà.', 'feelings'],
  ['calm', '/kɑːm/', 'adjective', 'bình tĩnh', 'Stay calm and listen carefully.', 'Hãy bình tĩnh và lắng nghe kỹ.', 'feelings'],

  ['phone', '/fəʊn/', 'noun', 'điện thoại', 'My phone needs charging.', 'Điện thoại của tôi cần được sạc.', 'technology'],
  ['screen', '/skriːn/', 'noun', 'màn hình', 'The words appear on the screen.', 'Các từ xuất hiện trên màn hình.', 'technology'],
  ['keyboard', '/ˈkiːbɔːd/', 'noun', 'bàn phím', 'This keyboard is easy to use.', 'Bàn phím này dễ sử dụng.', 'technology'],
  ['mouse', '/maʊs/', 'noun', 'chuột máy tính', 'Click the button with the mouse.', 'Hãy nhấp nút bằng chuột.', 'technology'],
  ['email', '/ˈiːmeɪl/', 'noun', 'thư điện tử', 'I sent you an email yesterday.', 'Tôi đã gửi email cho bạn hôm qua.', 'technology'],
  ['website', '/ˈwebsaɪt/', 'noun', 'trang web', 'The website loads quickly.', 'Trang web tải nhanh.', 'technology'],
  ['camera', '/ˈkæmərə/', 'noun', 'máy ảnh', 'This camera takes clear pictures.', 'Máy ảnh này chụp hình rõ nét.', 'technology'],
  ['video', '/ˈvɪdiəʊ/', 'noun', 'video', 'We watched a short video.', 'Chúng tôi đã xem một video ngắn.', 'technology'],
  ['message', '/ˈmesɪdʒ/', 'noun', 'tin nhắn', 'She left a message for you.', 'Cô ấy để lại một tin nhắn cho bạn.', 'technology'],
  ['online', '/ˌɒnˈlaɪn/', 'adverb', 'trực tuyến', 'You can study English online.', 'Bạn có thể học tiếng Anh trực tuyến.', 'technology'],

  ['book', '/bʊk/', 'noun', 'quyển sách', 'This book has many pictures.', 'Quyển sách này có nhiều hình ảnh.', 'daily-objects'],
  ['clock', '/klɒk/', 'noun', 'đồng hồ treo tường', 'The clock is above the door.', 'Đồng hồ ở phía trên cửa.', 'daily-objects'],
  ['watch', '/wɒtʃ/', 'noun', 'đồng hồ đeo tay', 'His watch is five minutes fast.', 'Đồng hồ của anh ấy chạy nhanh năm phút.', 'daily-objects'],
  ['bottle', '/ˈbɒtəl/', 'noun', 'chai', 'There is a bottle of water on the table.', 'Có một chai nước trên bàn.', 'daily-objects'],
  ['cup', '/kʌp/', 'noun', 'cốc', 'Would you like a cup of tea?', 'Bạn có muốn một cốc trà không?', 'daily-objects'],
  ['plate', '/pleɪt/', 'noun', 'đĩa', 'Put the fruit on a plate.', 'Hãy đặt trái cây lên đĩa.', 'daily-objects'],
  ['spoon', '/spuːn/', 'noun', 'thìa', 'Stir the coffee with a spoon.', 'Hãy khuấy cà phê bằng thìa.', 'daily-objects'],
  ['knife', '/naɪf/', 'noun', 'dao', 'Use a sharp knife carefully.', 'Hãy sử dụng dao sắc cẩn thận.', 'daily-objects'],
  ['box', '/bɒks/', 'noun', 'hộp', 'The shoes are inside the box.', 'Đôi giày ở trong hộp.', 'daily-objects'],
  ['light', '/laɪt/', 'noun', 'đèn', 'Please turn off the light.', 'Vui lòng tắt đèn.', 'daily-objects'],
];

export const englishVocabulary: EnglishVocabularyItem[] = rows.map((row, index) => {
  const id = `vocab-${String(index + 1).padStart(3, '0')}`;
  return {
    id,
    word: row[0],
    pronunciation: row[1],
    partOfSpeech: row[2],
    vietnameseMeaning: row[3],
    example: row[4],
    exampleTranslation: row[5],
    topicId: row[6],
    level: index < 100 ? 'A1' : 'A2',
    imagePath: `${id}.webp`,
    imageUrl: vocabularyImageUrls[id],
    sortOrder: index,
  };
});
