import { vocabularyImageUrls } from './image-manifest.generated';
import { EnglishVocabularyItem, VocabularyPartOfSpeech, VocabularyTopicId } from './types';

type VocabularyRow = readonly [
  word: string,
  pronunciation: string,
  partOfSpeech: VocabularyPartOfSpeech,
  vietnameseMeaning: string,
  example: string,
  exampleTranslation: string,
  topicId: VocabularyTopicId,
];

const rows: VocabularyRow[] = [
  ['go', '/ɡəʊ/', 'verb', 'đi', 'I go to school every day.', 'Tôi đi học mỗi ngày.', 'actions'],
  ['come', '/kʌm/', 'verb', 'đến', 'Please come here.', 'Hãy đến đây.', 'actions'],
  ['eat', '/iːt/', 'verb', 'ăn', 'We eat dinner at seven.', 'Chúng tôi ăn tối lúc bảy giờ.', 'actions'],
  ['drink', '/drɪŋk/', 'verb', 'uống', 'She drinks a glass of water.', 'Cô ấy uống một ly nước.', 'actions'],
  ['sleep', '/sliːp/', 'verb', 'ngủ', 'The baby is sleeping.', 'Em bé đang ngủ.', 'actions'],
  ['wake', '/weɪk/', 'verb', 'thức dậy', 'I wake up at six.', 'Tôi thức dậy lúc sáu giờ.', 'actions'],
  ['work', '/wɜːk/', 'verb', 'làm việc', 'My parents work at home.', 'Bố mẹ tôi làm việc tại nhà.', 'actions'],
  ['study', '/ˈstʌdi/', 'verb', 'học', 'They study English together.', 'Họ học tiếng Anh cùng nhau.', 'actions'],
  ['read', '/riːd/', 'verb', 'đọc', 'He reads a book before bed.', 'Anh ấy đọc sách trước khi ngủ.', 'actions'],
  ['write', '/raɪt/', 'verb', 'viết', 'Write your name here.', 'Hãy viết tên của bạn ở đây.', 'actions'],

  ['family', '/ˈfæməli/', 'noun', 'gia đình', 'My family lives in Vietnam.', 'Gia đình tôi sống ở Việt Nam.', 'people'],
  ['mother', '/ˈmʌðə/', 'noun', 'mẹ', 'My mother is a teacher.', 'Mẹ tôi là giáo viên.', 'people'],
  ['father', '/ˈfɑːðə/', 'noun', 'bố', 'Her father drives a bus.', 'Bố cô ấy lái xe buýt.', 'people'],
  ['parent', '/ˈpeərənt/', 'noun', 'phụ huynh', 'Every parent wants the best for their child.', 'Mỗi phụ huynh đều muốn điều tốt nhất cho con.', 'people'],
  ['child', '/tʃaɪld/', 'noun', 'đứa trẻ', 'The child is playing outside.', 'Đứa trẻ đang chơi bên ngoài.', 'people'],
  ['friend', '/frend/', 'noun', 'bạn bè', 'Lan is my best friend.', 'Lan là bạn thân nhất của tôi.', 'people'],
  ['man', '/mæn/', 'noun', 'người đàn ông', 'The man is wearing a blue shirt.', 'Người đàn ông đang mặc áo xanh.', 'people'],
  ['woman', '/ˈwʊmən/', 'noun', 'người phụ nữ', 'That woman is a doctor.', 'Người phụ nữ đó là bác sĩ.', 'people'],
  ['people', '/ˈpiːpəl/', 'noun', 'mọi người', 'Many people are in the park.', 'Có nhiều người trong công viên.', 'people'],
  ['baby', '/ˈbeɪbi/', 'noun', 'em bé', 'The baby has small hands.', 'Em bé có đôi tay nhỏ.', 'people'],

  ['house', '/haʊs/', 'noun', 'ngôi nhà', 'Their house has a red roof.', 'Ngôi nhà của họ có mái đỏ.', 'home'],
  ['room', '/ruːm/', 'noun', 'căn phòng', 'My room is clean and bright.', 'Phòng của tôi sạch sẽ và sáng sủa.', 'home'],
  ['door', '/dɔː/', 'noun', 'cánh cửa', 'Please close the door.', 'Vui lòng đóng cửa.', 'home'],
  ['window', '/ˈwɪndəʊ/', 'noun', 'cửa sổ', 'Open the window for some fresh air.', 'Mở cửa sổ để đón không khí trong lành.', 'home'],
  ['table', '/ˈteɪbəl/', 'noun', 'cái bàn', 'The keys are on the table.', 'Chìa khóa ở trên bàn.', 'home'],
  ['chair', '/tʃeə/', 'noun', 'cái ghế', 'Sit on this chair.', 'Hãy ngồi trên chiếc ghế này.', 'home'],
  ['bed', '/bed/', 'noun', 'cái giường', 'The cat is under the bed.', 'Con mèo ở dưới giường.', 'home'],
  ['kitchen', '/ˈkɪtʃɪn/', 'noun', 'nhà bếp', 'She is cooking in the kitchen.', 'Cô ấy đang nấu ăn trong bếp.', 'home'],
  ['bathroom', '/ˈbɑːθruːm/', 'noun', 'phòng tắm', 'The bathroom is next to my room.', 'Phòng tắm ở cạnh phòng tôi.', 'home'],
  ['key', '/kiː/', 'noun', 'chìa khóa', 'I cannot find my key.', 'Tôi không thể tìm thấy chìa khóa.', 'home'],

  ['food', '/fuːd/', 'noun', 'thức ăn', 'This food tastes good.', 'Món ăn này có vị ngon.', 'food'],
  ['water', '/ˈwɔːtə/', 'noun', 'nước', 'Drink more water every day.', 'Hãy uống nhiều nước hơn mỗi ngày.', 'food'],
  ['rice', '/raɪs/', 'noun', 'cơm; gạo', 'We usually eat rice for lunch.', 'Chúng tôi thường ăn cơm vào bữa trưa.', 'food'],
  ['bread', '/bred/', 'noun', 'bánh mì', 'I bought some fresh bread.', 'Tôi đã mua một ít bánh mì tươi.', 'food'],
  ['milk', '/mɪlk/', 'noun', 'sữa', 'The child drinks milk in the morning.', 'Đứa trẻ uống sữa vào buổi sáng.', 'food'],
  ['coffee', '/ˈkɒfi/', 'noun', 'cà phê', 'My father likes black coffee.', 'Bố tôi thích cà phê đen.', 'food'],
  ['tea', '/tiː/', 'noun', 'trà', 'Would you like some tea?', 'Bạn có muốn uống trà không?', 'food'],
  ['fruit', '/fruːt/', 'noun', 'trái cây', 'Fruit is good for your health.', 'Trái cây tốt cho sức khỏe.', 'food'],
  ['apple', '/ˈæpəl/', 'noun', 'quả táo', 'She eats an apple after lunch.', 'Cô ấy ăn một quả táo sau bữa trưa.', 'food'],
  ['egg', '/eɡ/', 'noun', 'quả trứng', 'There are two eggs in the bowl.', 'Có hai quả trứng trong tô.', 'food'],

  ['dog', '/dɒɡ/', 'noun', 'con chó', 'The dog runs in the garden.', 'Con chó chạy trong vườn.', 'nature'],
  ['cat', '/kæt/', 'noun', 'con mèo', 'Our cat has green eyes.', 'Con mèo của chúng tôi có mắt xanh.', 'nature'],
  ['bird', '/bɜːd/', 'noun', 'con chim', 'A bird is singing in the tree.', 'Một con chim đang hót trên cây.', 'nature'],
  ['fish', '/fɪʃ/', 'noun', 'con cá', 'The fish swims in clear water.', 'Con cá bơi trong làn nước trong.', 'nature'],
  ['horse', '/hɔːs/', 'noun', 'con ngựa', 'The horse is running fast.', 'Con ngựa đang chạy nhanh.', 'nature'],
  ['tree', '/triː/', 'noun', 'cây', 'That tree is very old.', 'Cái cây đó rất lâu năm.', 'nature'],
  ['flower', '/ˈflaʊə/', 'noun', 'bông hoa', 'This flower smells wonderful.', 'Bông hoa này có mùi rất thơm.', 'nature'],
  ['sun', '/sʌn/', 'noun', 'mặt trời', 'The sun rises in the east.', 'Mặt trời mọc ở phía đông.', 'nature'],
  ['rain', '/reɪn/', 'noun', 'mưa', 'The rain stopped this afternoon.', 'Mưa đã tạnh vào chiều nay.', 'nature'],
  ['river', '/ˈrɪvə/', 'noun', 'dòng sông', 'A long river runs through the city.', 'Một dòng sông dài chảy qua thành phố.', 'nature'],

  ['school', '/skuːl/', 'noun', 'trường học', 'The school is near my house.', 'Trường học ở gần nhà tôi.', 'places'],
  ['hospital', '/ˈhɒspɪtəl/', 'noun', 'bệnh viện', 'He works at the city hospital.', 'Anh ấy làm việc tại bệnh viện thành phố.', 'places'],
  ['market', '/ˈmɑːkɪt/', 'noun', 'chợ', 'My mother buys vegetables at the market.', 'Mẹ tôi mua rau ở chợ.', 'places'],
  ['shop', '/ʃɒp/', 'noun', 'cửa hàng', 'That shop sells books.', 'Cửa hàng đó bán sách.', 'places'],
  ['park', '/pɑːk/', 'noun', 'công viên', 'We walk in the park on Sunday.', 'Chúng tôi đi bộ trong công viên vào Chủ nhật.', 'places'],
  ['road', '/rəʊd/', 'noun', 'con đường', 'This road leads to the beach.', 'Con đường này dẫn đến bãi biển.', 'places'],
  ['city', '/ˈsɪti/', 'noun', 'thành phố', 'Ho Chi Minh City is very busy.', 'Thành phố Hồ Chí Minh rất nhộn nhịp.', 'places'],
  ['country', '/ˈkʌntri/', 'noun', 'đất nước', 'Vietnam is a beautiful country.', 'Việt Nam là một đất nước xinh đẹp.', 'places'],
  ['airport', '/ˈeəpɔːt/', 'noun', 'sân bay', 'We arrived at the airport early.', 'Chúng tôi đến sân bay sớm.', 'places'],
  ['station', '/ˈsteɪʃən/', 'noun', 'nhà ga; trạm', 'The train station is on the left.', 'Nhà ga ở bên trái.', 'places'],

  ['day', '/deɪ/', 'noun', 'ngày', 'It was a beautiful day.', 'Đó là một ngày đẹp trời.', 'time'],
  ['week', '/wiːk/', 'noun', 'tuần', 'I exercise three times a week.', 'Tôi tập thể dục ba lần một tuần.', 'time'],
  ['month', '/mʌnθ/', 'noun', 'tháng', 'Next month is my birthday.', 'Tháng sau là sinh nhật tôi.', 'time'],
  ['year', '/jɪə/', 'noun', 'năm', 'She visits her family every year.', 'Cô ấy thăm gia đình mỗi năm.', 'time'],
  ['today', '/təˈdeɪ/', 'adverb', 'hôm nay', 'I am busy today.', 'Hôm nay tôi bận.', 'time'],
  ['tomorrow', '/təˈmɒrəʊ/', 'adverb', 'ngày mai', 'We will meet tomorrow.', 'Chúng ta sẽ gặp nhau vào ngày mai.', 'time'],
  ['morning', '/ˈmɔːnɪŋ/', 'noun', 'buổi sáng', 'The air is cool in the morning.', 'Không khí mát mẻ vào buổi sáng.', 'time'],
  ['afternoon', '/ˌɑːftəˈnuːn/', 'noun', 'buổi chiều', 'See you this afternoon.', 'Hẹn gặp bạn chiều nay.', 'time'],
  ['evening', '/ˈiːvnɪŋ/', 'noun', 'buổi tối', 'We watch television in the evening.', 'Chúng tôi xem tivi vào buổi tối.', 'time'],
  ['night', '/naɪt/', 'noun', 'ban đêm', 'The stars are bright tonight.', 'Các vì sao sáng vào tối nay.', 'time'],

  ['good', '/ɡʊd/', 'adjective', 'tốt', 'You did a good job.', 'Bạn đã làm rất tốt.', 'descriptions'],
  ['bad', '/bæd/', 'adjective', 'xấu; tệ', 'The weather is bad today.', 'Thời tiết hôm nay rất xấu.', 'descriptions'],
  ['big', '/bɪɡ/', 'adjective', 'to; lớn', 'They live in a big house.', 'Họ sống trong một ngôi nhà lớn.', 'descriptions'],
  ['small', '/smɔːl/', 'adjective', 'nhỏ', 'I need a small bag.', 'Tôi cần một chiếc túi nhỏ.', 'descriptions'],
  ['new', '/njuː/', 'adjective', 'mới', 'This is my new phone.', 'Đây là điện thoại mới của tôi.', 'descriptions'],
  ['old', '/əʊld/', 'adjective', 'cũ; già', 'That is an old building.', 'Đó là một tòa nhà cũ.', 'descriptions'],
  ['happy', '/ˈhæpi/', 'adjective', 'vui vẻ', 'The children look happy.', 'Những đứa trẻ trông vui vẻ.', 'descriptions'],
  ['sad', '/sæd/', 'adjective', 'buồn', 'Why are you sad?', 'Tại sao bạn buồn?', 'descriptions'],
  ['hot', '/hɒt/', 'adjective', 'nóng', 'The soup is still hot.', 'Món súp vẫn còn nóng.', 'descriptions'],
  ['cold', '/kəʊld/', 'adjective', 'lạnh', 'It is cold outside.', 'Bên ngoài trời lạnh.', 'descriptions'],

  ['have', '/hæv/', 'verb', 'có', 'I have two brothers.', 'Tôi có hai anh em trai.', 'common-verbs'],
  ['make', '/meɪk/', 'verb', 'làm; tạo ra', 'We make breakfast together.', 'Chúng tôi cùng nhau làm bữa sáng.', 'common-verbs'],
  ['take', '/teɪk/', 'verb', 'lấy; mang', 'Take an umbrella with you.', 'Hãy mang theo một chiếc ô.', 'common-verbs'],
  ['give', '/ɡɪv/', 'verb', 'đưa; cho', 'Please give me the book.', 'Vui lòng đưa tôi cuốn sách.', 'common-verbs'],
  ['get', '/ɡet/', 'verb', 'nhận; có được', 'I get many emails every day.', 'Tôi nhận nhiều email mỗi ngày.', 'common-verbs'],
  ['know', '/nəʊ/', 'verb', 'biết', 'Do you know her name?', 'Bạn có biết tên cô ấy không?', 'common-verbs'],
  ['think', '/θɪŋk/', 'verb', 'suy nghĩ', 'I think this answer is right.', 'Tôi nghĩ câu trả lời này đúng.', 'common-verbs'],
  ['want', '/wɒnt/', 'verb', 'muốn', 'They want a new car.', 'Họ muốn một chiếc xe mới.', 'common-verbs'],
  ['need', '/niːd/', 'verb', 'cần', 'We need more time.', 'Chúng tôi cần thêm thời gian.', 'common-verbs'],
  ['like', '/laɪk/', 'verb', 'thích', 'I like Vietnamese food.', 'Tôi thích đồ ăn Việt Nam.', 'common-verbs'],

  ['say', '/seɪ/', 'verb', 'nói', 'She says hello to everyone.', 'Cô ấy chào mọi người.', 'communication'],
  ['tell', '/tel/', 'verb', 'kể; bảo', 'Tell me your story.', 'Hãy kể cho tôi câu chuyện của bạn.', 'communication'],
  ['speak', '/spiːk/', 'verb', 'nói; phát biểu', 'Can you speak English?', 'Bạn có thể nói tiếng Anh không?', 'communication'],
  ['ask', '/ɑːsk/', 'verb', 'hỏi', 'I want to ask a question.', 'Tôi muốn hỏi một câu.', 'communication'],
  ['answer', '/ˈɑːnsə/', 'verb', 'trả lời', 'Please answer the phone.', 'Vui lòng nghe điện thoại.', 'communication'],
  ['listen', '/ˈlɪsən/', 'verb', 'lắng nghe', 'Listen carefully to the teacher.', 'Hãy chăm chú nghe giáo viên.', 'communication'],
  ['hear', '/hɪə/', 'verb', 'nghe thấy', 'I can hear music upstairs.', 'Tôi có thể nghe thấy nhạc ở tầng trên.', 'communication'],
  ['see', '/siː/', 'verb', 'nhìn thấy', 'I can see the mountains from here.', 'Tôi có thể nhìn thấy núi từ đây.', 'communication'],
  ['look', '/lʊk/', 'verb', 'nhìn', 'Look at this picture.', 'Hãy nhìn vào bức tranh này.', 'communication'],
  ['help', '/help/', 'verb', 'giúp đỡ', 'Could you help me, please?', 'Bạn có thể giúp tôi được không?', 'communication'],
];

export const englishVocabulary: EnglishVocabularyItem[] = rows.map((row, index) => {
  const id = `vocab-${String(index + 1).padStart(3, '0')}`;
  return {
    id,
    word: row[0],
    pronunciation: row[1],
    partOfSpeech: row[2],
    vietnameseMeaning: row[3],
    example: row[4],
    exampleTranslation: row[5],
    topicId: row[6],
    level: 'A1',
    imagePath: `${id}.webp`,
    imageUrl: vocabularyImageUrls[id],
    sortOrder: index,
  };
});
