import { ChemicalElementItem, ElementCategory } from './types';

type ElementRow = readonly [
  symbol: string,
  vietnameseName: string,
  internationalName: string,
  atomicMass: string,
  period: number,
  group: number | undefined,
  category: ElementCategory,
];

const rows: ElementRow[] = [
  ['H', 'Hiđrô', 'Hydrogen', '1.008', 1, 1, 'reactive-nonmetal'],
  ['He', 'Heli', 'Helium', '4.0026', 1, 18, 'noble-gas'],
  ['Li', 'Liti', 'Lithium', '6.94', 2, 1, 'alkali-metal'],
  ['Be', 'Berili', 'Beryllium', '9.0122', 2, 2, 'alkaline-earth-metal'],
  ['B', 'Bo', 'Boron', '10.81', 2, 13, 'metalloid'],
  ['C', 'Cacbon', 'Carbon', '12.011', 2, 14, 'reactive-nonmetal'],
  ['N', 'Nitơ', 'Nitrogen', '14.007', 2, 15, 'reactive-nonmetal'],
  ['O', 'Oxi', 'Oxygen', '15.999', 2, 16, 'reactive-nonmetal'],
  ['F', 'Flo', 'Fluorine', '18.998', 2, 17, 'reactive-nonmetal'],
  ['Ne', 'Neon', 'Neon', '20.180', 2, 18, 'noble-gas'],
  ['Na', 'Natri', 'Sodium', '22.990', 3, 1, 'alkali-metal'],
  ['Mg', 'Magie', 'Magnesium', '24.305', 3, 2, 'alkaline-earth-metal'],
  ['Al', 'Nhôm', 'Aluminium', '26.982', 3, 13, 'post-transition-metal'],
  ['Si', 'Silic', 'Silicon', '28.085', 3, 14, 'metalloid'],
  ['P', 'Photpho', 'Phosphorus', '30.974', 3, 15, 'reactive-nonmetal'],
  ['S', 'Lưu huỳnh', 'Sulfur', '32.06', 3, 16, 'reactive-nonmetal'],
  ['Cl', 'Clo', 'Chlorine', '35.45', 3, 17, 'reactive-nonmetal'],
  ['Ar', 'Argon', 'Argon', '39.948', 3, 18, 'noble-gas'],
  ['K', 'Kali', 'Potassium', '39.098', 4, 1, 'alkali-metal'],
  ['Ca', 'Canxi', 'Calcium', '40.078', 4, 2, 'alkaline-earth-metal'],
  ['Sc', 'Scandi', 'Scandium', '44.956', 4, 3, 'transition-metal'],
  ['Ti', 'Titan', 'Titanium', '47.867', 4, 4, 'transition-metal'],
  ['V', 'Vanadi', 'Vanadium', '50.942', 4, 5, 'transition-metal'],
  ['Cr', 'Crom', 'Chromium', '51.996', 4, 6, 'transition-metal'],
  ['Mn', 'Mangan', 'Manganese', '54.938', 4, 7, 'transition-metal'],
  ['Fe', 'Sắt', 'Iron', '55.845', 4, 8, 'transition-metal'],
  ['Co', 'Coban', 'Cobalt', '58.933', 4, 9, 'transition-metal'],
  ['Ni', 'Niken', 'Nickel', '58.693', 4, 10, 'transition-metal'],
  ['Cu', 'Đồng', 'Copper', '63.546', 4, 11, 'transition-metal'],
  ['Zn', 'Kẽm', 'Zinc', '65.38', 4, 12, 'transition-metal'],
  ['Ga', 'Gali', 'Gallium', '69.723', 4, 13, 'post-transition-metal'],
  ['Ge', 'Gecmani', 'Germanium', '72.630', 4, 14, 'metalloid'],
  ['As', 'Asen', 'Arsenic', '74.922', 4, 15, 'metalloid'],
  ['Se', 'Selen', 'Selenium', '78.971', 4, 16, 'reactive-nonmetal'],
  ['Br', 'Brôm', 'Bromine', '79.904', 4, 17, 'reactive-nonmetal'],
  ['Kr', 'Krypton', 'Krypton', '83.798', 4, 18, 'noble-gas'],
  ['Rb', 'Rubidi', 'Rubidium', '85.468', 5, 1, 'alkali-metal'],
  ['Sr', 'Stronti', 'Strontium', '87.62', 5, 2, 'alkaline-earth-metal'],
  ['Y', 'Ytri', 'Yttrium', '88.906', 5, 3, 'transition-metal'],
  ['Zr', 'Zirconi', 'Zirconium', '91.224', 5, 4, 'transition-metal'],
  ['Nb', 'Niobi', 'Niobium', '92.906', 5, 5, 'transition-metal'],
  ['Mo', 'Molypden', 'Molybdenum', '95.95', 5, 6, 'transition-metal'],
  ['Tc', 'Tecneti', 'Technetium', '[98]', 5, 7, 'transition-metal'],
  ['Ru', 'Ruteni', 'Ruthenium', '101.07', 5, 8, 'transition-metal'],
  ['Rh', 'Rhodi', 'Rhodium', '102.91', 5, 9, 'transition-metal'],
  ['Pd', 'Paladi', 'Palladium', '106.42', 5, 10, 'transition-metal'],
  ['Ag', 'Bạc', 'Silver', '107.87', 5, 11, 'transition-metal'],
  ['Cd', 'Cadimi', 'Cadmium', '112.41', 5, 12, 'transition-metal'],
  ['In', 'Indi', 'Indium', '114.82', 5, 13, 'post-transition-metal'],
  ['Sn', 'Thiếc', 'Tin', '118.71', 5, 14, 'post-transition-metal'],
  ['Sb', 'Antimon', 'Antimony', '121.76', 5, 15, 'metalloid'],
  ['Te', 'Telua', 'Tellurium', '127.60', 5, 16, 'metalloid'],
  ['I', 'Iốt', 'Iodine', '126.90', 5, 17, 'reactive-nonmetal'],
  ['Xe', 'Xenon', 'Xenon', '131.29', 5, 18, 'noble-gas'],
  ['Cs', 'Xêsi', 'Caesium', '132.91', 6, 1, 'alkali-metal'],
  ['Ba', 'Bari', 'Barium', '137.33', 6, 2, 'alkaline-earth-metal'],
  ['La', 'Lantan', 'Lanthanum', '138.91', 6, undefined, 'lanthanide'],
  ['Ce', 'Xeri', 'Cerium', '140.12', 6, undefined, 'lanthanide'],
  ['Pr', 'Praseodymi', 'Praseodymium', '140.91', 6, undefined, 'lanthanide'],
  ['Nd', 'Neodymi', 'Neodymium', '144.24', 6, undefined, 'lanthanide'],
  ['Pm', 'Prometi', 'Promethium', '[145]', 6, undefined, 'lanthanide'],
  ['Sm', 'Samari', 'Samarium', '150.36', 6, undefined, 'lanthanide'],
  ['Eu', 'Europi', 'Europium', '151.96', 6, undefined, 'lanthanide'],
  ['Gd', 'Gadolini', 'Gadolinium', '157.25', 6, undefined, 'lanthanide'],
  ['Tb', 'Terbi', 'Terbium', '158.93', 6, undefined, 'lanthanide'],
  ['Dy', 'Dysprosi', 'Dysprosium', '162.50', 6, undefined, 'lanthanide'],
  ['Ho', 'Holmi', 'Holmium', '164.93', 6, undefined, 'lanthanide'],
  ['Er', 'Erbi', 'Erbium', '167.26', 6, undefined, 'lanthanide'],
  ['Tm', 'Tuli', 'Thulium', '168.93', 6, undefined, 'lanthanide'],
  ['Yb', 'Ytterbi', 'Ytterbium', '173.05', 6, undefined, 'lanthanide'],
  ['Lu', 'Luteti', 'Lutetium', '174.97', 6, 3, 'lanthanide'],
  ['Hf', 'Hafni', 'Hafnium', '178.49', 6, 4, 'transition-metal'],
  ['Ta', 'Tantan', 'Tantalum', '180.95', 6, 5, 'transition-metal'],
  ['W', 'Vonfram', 'Tungsten', '183.84', 6, 6, 'transition-metal'],
  ['Re', 'Rheni', 'Rhenium', '186.21', 6, 7, 'transition-metal'],
  ['Os', 'Osmi', 'Osmium', '190.23', 6, 8, 'transition-metal'],
  ['Ir', 'Iridi', 'Iridium', '192.22', 6, 9, 'transition-metal'],
  ['Pt', 'Platin', 'Platinum', '195.08', 6, 10, 'transition-metal'],
  ['Au', 'Vàng', 'Gold', '196.97', 6, 11, 'transition-metal'],
  ['Hg', 'Thủy ngân', 'Mercury', '200.59', 6, 12, 'transition-metal'],
  ['Tl', 'Tali', 'Thallium', '204.38', 6, 13, 'post-transition-metal'],
  ['Pb', 'Chì', 'Lead', '207.2', 6, 14, 'post-transition-metal'],
  ['Bi', 'Bitmut', 'Bismuth', '208.98', 6, 15, 'post-transition-metal'],
  ['Po', 'Poloni', 'Polonium', '[209]', 6, 16, 'post-transition-metal'],
  ['At', 'Astatin', 'Astatine', '[210]', 6, 17, 'metalloid'],
  ['Rn', 'Radon', 'Radon', '[222]', 6, 18, 'noble-gas'],
  ['Fr', 'Franxi', 'Francium', '[223]', 7, 1, 'alkali-metal'],
  ['Ra', 'Radi', 'Radium', '[226]', 7, 2, 'alkaline-earth-metal'],
  ['Ac', 'Actini', 'Actinium', '[227]', 7, undefined, 'actinide'],
  ['Th', 'Thori', 'Thorium', '232.04', 7, undefined, 'actinide'],
  ['Pa', 'Protactini', 'Protactinium', '231.04', 7, undefined, 'actinide'],
  ['U', 'Urani', 'Uranium', '238.03', 7, undefined, 'actinide'],
  ['Np', 'Neptuni', 'Neptunium', '[237]', 7, undefined, 'actinide'],
  ['Pu', 'Plutoni', 'Plutonium', '[244]', 7, undefined, 'actinide'],
  ['Am', 'Americi', 'Americium', '[243]', 7, undefined, 'actinide'],
  ['Cm', 'Curi', 'Curium', '[247]', 7, undefined, 'actinide'],
  ['Bk', 'Berkeli', 'Berkelium', '[247]', 7, undefined, 'actinide'],
  ['Cf', 'Californi', 'Californium', '[251]', 7, undefined, 'actinide'],
  ['Es', 'Einsteini', 'Einsteinium', '[252]', 7, undefined, 'actinide'],
  ['Fm', 'Fermi', 'Fermium', '[257]', 7, undefined, 'actinide'],
  ['Md', 'Mendelevi', 'Mendelevium', '[258]', 7, undefined, 'actinide'],
  ['No', 'Nobeli', 'Nobelium', '[259]', 7, undefined, 'actinide'],
  ['Lr', 'Lawrenci', 'Lawrencium', '[266]', 7, 3, 'actinide'],
  ['Rf', 'Rutherfordi', 'Rutherfordium', '[267]', 7, 4, 'transition-metal'],
  ['Db', 'Dubni', 'Dubnium', '[268]', 7, 5, 'transition-metal'],
  ['Sg', 'Seaborgi', 'Seaborgium', '[269]', 7, 6, 'transition-metal'],
  ['Bh', 'Bohri', 'Bohrium', '[270]', 7, 7, 'transition-metal'],
  ['Hs', 'Hassi', 'Hassium', '[277]', 7, 8, 'transition-metal'],
  ['Mt', 'Meitneri', 'Meitnerium', '[278]', 7, 9, 'unknown'],
  ['Ds', 'Darmstadti', 'Darmstadtium', '[281]', 7, 10, 'unknown'],
  ['Rg', 'Roentgeni', 'Roentgenium', '[282]', 7, 11, 'unknown'],
  ['Cn', 'Copernixi', 'Copernicium', '[285]', 7, 12, 'post-transition-metal'],
  ['Nh', 'Nihoni', 'Nihonium', '[286]', 7, 13, 'unknown'],
  ['Fl', 'Flerovi', 'Flerovium', '[289]', 7, 14, 'post-transition-metal'],
  ['Mc', 'Moscovi', 'Moscovium', '[290]', 7, 15, 'unknown'],
  ['Lv', 'Livermori', 'Livermorium', '[293]', 7, 16, 'unknown'],
  ['Ts', 'Tennessine', 'Tennessine', '[294]', 7, 17, 'unknown'],
  ['Og', 'Oganesson', 'Oganesson', '[294]', 7, 18, 'unknown'],
];

export const chemicalElements: ChemicalElementItem[] = rows.map((row, index) => ({
  id: `element-${index + 1}`,
  atomicNumber: index + 1,
  symbol: row[0],
  vietnameseName: row[1],
  internationalName: row[2],
  atomicMass: row[3],
  period: row[4],
  group: row[5],
  category: row[6],
  sortOrder: index,
}));
