insert into public.modules (id,name,category,description,icon,color,is_active,display_order,tags,metadata)
values ('memory-cards','Nhớ bài Tây','memory','Mã hóa mỗi lá bằng một hình trong hệ 100 số, tạo câu chuyện và nhớ chính xác thứ tự bộ bài.','club','#ef4444',true,2,ARRAY['trí nhớ','bài tây','cung điện trí nhớ'],'{"subtitle":"52 lá • Hệ hình 01–52","status":"available","totalItems":52}'::jsonb)
on conflict (id) do update set name=excluded.name,category=excluded.category,description=excluded.description,icon=excluded.icon,color=excluded.color,is_active=excluded.is_active,display_order=excluded.display_order,tags=excluded.tags,metadata=excluded.metadata,updated_at=now();

delete from public.module_groups where module_id='memory-cards';
insert into public.module_groups (module_id,id,name,description,sort_order,metadata) values
('memory-cards','spades','♠ Bích','13 lá chất Bích',1,'{"match":{"field":"suit","equals":"spades"}}'),
('memory-cards','hearts','♥ Cơ','13 lá chất Cơ',2,'{"match":{"field":"suit","equals":"hearts"}}'),
('memory-cards','diamonds','♦ Rô','13 lá chất Rô',3,'{"match":{"field":"suit","equals":"diamonds"}}'),
('memory-cards','clubs','♣ Tép','13 lá chất Tép',4,'{"match":{"field":"suit","equals":"clubs"}}'),
('memory-cards','all','Cả bộ','Toàn bộ 52 lá',5,'{"allItems":true}');

delete from public.module_items where module_id='memory-cards';
insert into public.module_items (module_id,id,code,name,image_url,group_id,tags,attributes,sort_order) values
('memory-cards','a-spades','A♠','Át Bích','/playing-cards/a_of_spades.svg','spades',ARRAY['playing-card','memory-system'],'{"suit":"spades","rank":"a","mnemonicNumber":"00","mnemonicName":"Quả trứng","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/00.webp"}'::jsonb,0),
('memory-cards','2-spades','2♠','2 Bích','/playing-cards/2_of_spades.svg','spades',ARRAY['playing-card','memory-system'],'{"suit":"spades","rank":"2","mnemonicNumber":"01","mnemonicName":"Cây dù","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/01.webp"}'::jsonb,1),
('memory-cards','3-spades','3♠','3 Bích','/playing-cards/3_of_spades.svg','spades',ARRAY['playing-card','memory-system'],'{"suit":"spades","rank":"3","mnemonicNumber":"02","mnemonicName":"Con vịt","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/02.webp"}'::jsonb,2),
('memory-cards','4-spades','4♠','4 Bích','/playing-cards/4_of_spades.svg','spades',ARRAY['playing-card','memory-system'],'{"suit":"spades","rank":"4","mnemonicNumber":"03","mnemonicName":"Trái tim","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/03.webp"}'::jsonb,3),
('memory-cards','5-spades','5♠','5 Bích','/playing-cards/5_of_spades.svg','spades',ARRAY['playing-card','memory-system'],'{"suit":"spades","rank":"5","mnemonicNumber":"04","mnemonicName":"Cái ghế","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/04.webp"}'::jsonb,4),
('memory-cards','6-spades','6♠','6 Bích','/playing-cards/6_of_spades.svg','spades',ARRAY['playing-card','memory-system'],'{"suit":"spades","rank":"6","mnemonicNumber":"05","mnemonicName":"Quả táo","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/05.webp"}'::jsonb,5),
('memory-cards','7-spades','7♠','7 Bích','/playing-cards/7_of_spades.svg','spades',ARRAY['playing-card','memory-system'],'{"suit":"spades","rank":"7","mnemonicNumber":"06","mnemonicName":"Vỏ ốc","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/06.webp"}'::jsonb,6),
('memory-cards','8-spades','8♠','8 Bích','/playing-cards/8_of_spades.svg','spades',ARRAY['playing-card','memory-system'],'{"suit":"spades","rank":"8","mnemonicNumber":"07","mnemonicName":"Cái rìu","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/07.webp"}'::jsonb,7),
('memory-cards','9-spades','9♠','9 Bích','/playing-cards/9_of_spades.svg','spades',ARRAY['playing-card','memory-system'],'{"suit":"spades","rank":"9","mnemonicNumber":"08","mnemonicName":"Người tuyết","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/08.webp"}'::jsonb,8),
('memory-cards','10-spades','10♠','10 Bích','/playing-cards/10_of_spades.svg','spades',ARRAY['playing-card','memory-system'],'{"suit":"spades","rank":"10","mnemonicNumber":"09","mnemonicName":"Hươu cao cổ","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/09.webp"}'::jsonb,9),
('memory-cards','j-spades','J♠','J Bích','/playing-cards/j_of_spades.svg','spades',ARRAY['playing-card','memory-system'],'{"suit":"spades","rank":"j","mnemonicNumber":"10","mnemonicName":"Con heo","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/10.webp"}'::jsonb,10),
('memory-cards','q-spades','Q♠','Q Bích','/playing-cards/q_of_spades.svg','spades',ARRAY['playing-card','memory-system'],'{"suit":"spades","rank":"q","mnemonicNumber":"11","mnemonicName":"Cái thang","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/11.webp"}'::jsonb,11),
('memory-cards','k-spades','K♠','K Bích','/playing-cards/k_of_spades.svg','spades',ARRAY['playing-card','memory-system'],'{"suit":"spades","rank":"k","mnemonicNumber":"12","mnemonicName":"Cá mập","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/12.webp"}'::jsonb,12),
('memory-cards','a-hearts','A♥','Át Cơ','/playing-cards/a_of_hearts.svg','hearts',ARRAY['playing-card','memory-system'],'{"suit":"hearts","rank":"a","mnemonicNumber":"13","mnemonicName":"Con bướm","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/13.webp"}'::jsonb,13),
('memory-cards','2-hearts','2♥','2 Cơ','/playing-cards/2_of_hearts.svg','hearts',ARRAY['playing-card','memory-system'],'{"suit":"hearts","rank":"2","mnemonicNumber":"14","mnemonicName":"Thuyền buồm","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/14.webp"}'::jsonb,14),
('memory-cards','3-hearts','3♥','3 Cơ','/playing-cards/3_of_hearts.svg','hearts',ARRAY['playing-card','memory-system'],'{"suit":"hearts","rank":"3","mnemonicNumber":"15","mnemonicName":"Túi tiền","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/15.webp"}'::jsonb,15),
('memory-cards','4-hearts','4♥','4 Cơ','/playing-cards/4_of_hearts.svg','hearts',ARRAY['playing-card','memory-system'],'{"suit":"hearts","rank":"4","mnemonicNumber":"16","mnemonicName":"Con ốc sên","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/16.webp"}'::jsonb,16),
('memory-cards','5-hearts','5♥','5 Cơ','/playing-cards/5_of_hearts.svg','hearts',ARRAY['playing-card','memory-system'],'{"suit":"hearts","rank":"5","mnemonicNumber":"17","mnemonicName":"Nốt nhạc","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/17.webp"}'::jsonb,17),
('memory-cards','6-hearts','6♥','6 Cơ','/playing-cards/6_of_hearts.svg','hearts',ARRAY['playing-card','memory-system'],'{"suit":"hearts","rank":"6","mnemonicNumber":"18","mnemonicName":"Đèn giao thông","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/18.webp"}'::jsonb,18),
('memory-cards','7-hearts','7♥','7 Cơ','/playing-cards/7_of_hearts.svg','hearts',ARRAY['playing-card','memory-system'],'{"suit":"hearts","rank":"7","mnemonicNumber":"19","mnemonicName":"Con chó","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/19.webp"}'::jsonb,19),
('memory-cards','8-hearts','8♥','8 Cơ','/playing-cards/8_of_hearts.svg','hearts',ARRAY['playing-card','memory-system'],'{"suit":"hearts","rank":"8","mnemonicNumber":"20","mnemonicName":"Quả bom","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/20.webp"}'::jsonb,20),
('memory-cards','9-hearts','9♥','9 Cơ','/playing-cards/9_of_hearts.svg','hearts',ARRAY['playing-card','memory-system'],'{"suit":"hearts","rank":"9","mnemonicNumber":"21","mnemonicName":"Cây nến","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/21.webp"}'::jsonb,21),
('memory-cards','10-hearts','10♥','10 Cơ','/playing-cards/10_of_hearts.svg','hearts',ARRAY['playing-card','memory-system'],'{"suit":"hearts","rank":"10","mnemonicNumber":"22","mnemonicName":"Thiên nga","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/22.webp"}'::jsonb,22),
('memory-cards','j-hearts','J♥','J Cơ','/playing-cards/j_of_hearts.svg','hearts',ARRAY['playing-card','memory-system'],'{"suit":"hearts","rank":"j","mnemonicNumber":"23","mnemonicName":"Con công","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/23.webp"}'::jsonb,23),
('memory-cards','q-hearts','Q♥','Q Cơ','/playing-cards/q_of_hearts.svg','hearts',ARRAY['playing-card','memory-system'],'{"suit":"hearts","rank":"q","mnemonicNumber":"24","mnemonicName":"Con sóc","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/24.webp"}'::jsonb,24),
('memory-cards','k-hearts','K♥','K Cơ','/playing-cards/k_of_hearts.svg','hearts',ARRAY['playing-card','memory-system'],'{"suit":"hearts","rank":"k","mnemonicNumber":"25","mnemonicName":"Cần cẩu","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/25.webp"}'::jsonb,25),
('memory-cards','a-diamonds','A♦','Át Rô','/playing-cards/a_of_diamonds.svg','diamonds',ARRAY['playing-card','memory-system'],'{"suit":"diamonds","rank":"a","mnemonicNumber":"26","mnemonicName":"Gà trống","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/26.webp"}'::jsonb,26),
('memory-cards','2-diamonds','2♦','2 Rô','/playing-cards/2_of_diamonds.svg','diamonds',ARRAY['playing-card','memory-system'],'{"suit":"diamonds","rank":"2","mnemonicNumber":"27","mnemonicName":"Con chuột","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/27.webp"}'::jsonb,27),
('memory-cards','3-diamonds','3♦','3 Rô','/playing-cards/3_of_diamonds.svg','diamonds',ARRAY['playing-card','memory-system'],'{"suit":"diamonds","rank":"3","mnemonicNumber":"28","mnemonicName":"Cà rốt và thỏ","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/28.webp"}'::jsonb,28),
('memory-cards','4-diamonds','4♦','4 Rô','/playing-cards/4_of_diamonds.svg','diamonds',ARRAY['playing-card','memory-system'],'{"suit":"diamonds","rank":"4","mnemonicNumber":"29","mnemonicName":"Chuột máy tính","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/29.webp"}'::jsonb,29),
('memory-cards','5-diamonds','5♦','5 Rô','/playing-cards/5_of_diamonds.svg','diamonds',ARRAY['playing-card','memory-system'],'{"suit":"diamonds","rank":"5","mnemonicNumber":"30","mnemonicName":"Núi và mặt trời","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/30.webp"}'::jsonb,30),
('memory-cards','6-diamonds','6♦','6 Rô','/playing-cards/6_of_diamonds.svg','diamonds',ARRAY['playing-card','memory-system'],'{"suit":"diamonds","rank":"6","mnemonicNumber":"31","mnemonicName":"Bóng đèn","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/31.webp"}'::jsonb,31),
('memory-cards','7-diamonds','7♦','7 Rô','/playing-cards/7_of_diamonds.svg','diamonds',ARRAY['playing-card','memory-system'],'{"suit":"diamonds","rank":"7","mnemonicNumber":"32","mnemonicName":"Vòi sen","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/32.webp"}'::jsonb,32),
('memory-cards','8-diamonds','8♦','8 Rô','/playing-cards/8_of_diamonds.svg','diamonds',ARRAY['playing-card','memory-system'],'{"suit":"diamonds","rank":"8","mnemonicNumber":"33","mnemonicName":"Cúc áo","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/33.webp"}'::jsonb,33),
('memory-cards','9-diamonds','9♦','9 Rô','/playing-cards/9_of_diamonds.svg','diamonds',ARRAY['playing-card','memory-system'],'{"suit":"diamonds","rank":"9","mnemonicNumber":"34","mnemonicName":"Kim cương","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/34.webp"}'::jsonb,34),
('memory-cards','10-diamonds','10♦','10 Rô','/playing-cards/10_of_diamonds.svg','diamonds',ARRAY['playing-card','memory-system'],'{"suit":"diamonds","rank":"10","mnemonicNumber":"35","mnemonicName":"Đu đủ","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/35.webp"}'::jsonb,35),
('memory-cards','j-diamonds','J♦','J Rô','/playing-cards/j_of_diamonds.svg','diamonds',ARRAY['playing-card','memory-system'],'{"suit":"diamonds","rank":"j","mnemonicNumber":"36","mnemonicName":"Hoa hồng","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/36.webp"}'::jsonb,36),
('memory-cards','q-diamonds','Q♦','Q Rô','/playing-cards/q_of_diamonds.svg','diamonds',ARRAY['playing-card','memory-system'],'{"suit":"diamonds","rank":"q","mnemonicNumber":"37","mnemonicName":"Loa cầm tay","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/37.webp"}'::jsonb,37),
('memory-cards','k-diamonds','K♦','K Rô','/playing-cards/k_of_diamonds.svg','diamonds',ARRAY['playing-card','memory-system'],'{"suit":"diamonds","rank":"k","mnemonicNumber":"38","mnemonicName":"Nhẫn kim cương","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/38.webp"}'::jsonb,38),
('memory-cards','a-clubs','A♣','Át Tép','/playing-cards/a_of_clubs.svg','clubs',ARRAY['playing-card','memory-system'],'{"suit":"clubs","rank":"a","mnemonicNumber":"39","mnemonicName":"Tê giác","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/39.webp"}'::jsonb,39),
('memory-cards','2-clubs','2♣','2 Tép','/playing-cards/2_of_clubs.svg','clubs',ARRAY['playing-card','memory-system'],'{"suit":"clubs","rank":"2","mnemonicNumber":"40","mnemonicName":"Bút chì","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/40.webp"}'::jsonb,40),
('memory-cards','3-clubs','3♣','3 Tép','/playing-cards/3_of_clubs.svg','clubs',ARRAY['playing-card','memory-system'],'{"suit":"clubs","rank":"3","mnemonicNumber":"41","mnemonicName":"Bình cứu hỏa","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/41.webp"}'::jsonb,41),
('memory-cards','4-clubs','4♣','4 Tép','/playing-cards/4_of_clubs.svg','clubs',ARRAY['playing-card','memory-system'],'{"suit":"clubs","rank":"4","mnemonicNumber":"42","mnemonicName":"Cây diều","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/42.webp"}'::jsonb,42),
('memory-cards','5-clubs','5♣','5 Tép','/playing-cards/5_of_clubs.svg','clubs',ARRAY['playing-card','memory-system'],'{"suit":"clubs","rank":"5","mnemonicNumber":"43","mnemonicName":"Người lướt sóng","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/43.webp"}'::jsonb,43),
('memory-cards','6-clubs','6♣','6 Tép','/playing-cards/6_of_clubs.svg','clubs',ARRAY['playing-card','memory-system'],'{"suit":"clubs","rank":"6","mnemonicNumber":"44","mnemonicName":"Rừng thông","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/44.webp"}'::jsonb,44),
('memory-cards','7-clubs','7♣','7 Tép','/playing-cards/7_of_clubs.svg','clubs',ARRAY['playing-card','memory-system'],'{"suit":"clubs","rank":"7","mnemonicNumber":"45","mnemonicName":"Nam châm","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/45.webp"}'::jsonb,45),
('memory-cards','8-clubs','8♣','8 Tép','/playing-cards/8_of_clubs.svg','clubs',ARRAY['playing-card','memory-system'],'{"suit":"clubs","rank":"8","mnemonicNumber":"46","mnemonicName":"Cung tên","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/46.webp"}'::jsonb,46),
('memory-cards','9-clubs','9♣','9 Tép','/playing-cards/9_of_clubs.svg','clubs',ARRAY['playing-card','memory-system'],'{"suit":"clubs","rank":"9","mnemonicNumber":"47","mnemonicName":"Cầu thang","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/47.webp"}'::jsonb,47),
('memory-cards','10-clubs','10♣','10 Tép','/playing-cards/10_of_clubs.svg','clubs',ARRAY['playing-card','memory-system'],'{"suit":"clubs","rank":"10","mnemonicNumber":"48","mnemonicName":"Doremon","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/48.webp"}'::jsonb,48),
('memory-cards','j-clubs','J♣','J Tép','/playing-cards/j_of_clubs.svg','clubs',ARRAY['playing-card','memory-system'],'{"suit":"clubs","rank":"j","mnemonicNumber":"49","mnemonicName":"Cái ly","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/49.webp"}'::jsonb,49),
('memory-cards','q-clubs','Q♣','Q Tép','/playing-cards/q_of_clubs.svg','clubs',ARRAY['playing-card','memory-system'],'{"suit":"clubs","rank":"q","mnemonicNumber":"50","mnemonicName":"Xe đạp","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/50.webp"}'::jsonb,50),
('memory-cards','k-clubs','K♣','K Tép','/playing-cards/k_of_clubs.svg','clubs',ARRAY['playing-card','memory-system'],'{"suit":"clubs","rank":"k","mnemonicNumber":"51","mnemonicName":"Sư tử","mnemonicImageUrl":"https://enehanbjjoofswlcawik.supabase.co/storage/v1/object/public/number-images/51.webp"}'::jsonb,51);

-- Cards use the existing mnemonic images 01–52 (not 00–51).
update public.module_items as card
set attributes = card.attributes || jsonb_build_object(
  'mnemonicNumber', number_item.code,
  'mnemonicName', number_item.name,
  'mnemonicImageUrl', number_item.image_url
)
from public.module_items as number_item
where card.module_id = 'memory-cards'
  and number_item.module_id = 'numbers-00-99'
  and number_item.sort_order = card.sort_order + 1;

update public.modules
set metadata = jsonb_set(metadata, '{subtitle}', '"52 lá • Hệ hình 01–52"'::jsonb),
    updated_at = now()
where id = 'memory-cards';
