import { NumberMemoryItem } from './types';

export const numberMemoryItems: NumberMemoryItem[] = [
  { id: 'number-00', number: '00', name: 'Quả trứng', imageUrl: '/number-images/00.webp', sortOrder: 0 },
  { id: 'number-01', number: '01', name: 'Cây dù', imageUrl: '/number-images/01.webp', sortOrder: 1 },
  { id: 'number-02', number: '02', name: 'Con vịt', imageUrl: '/number-images/02.webp', sortOrder: 2 },
  { id: 'number-03', number: '03', name: 'Trái tim', imageUrl: '/number-images/03.webp', sortOrder: 3 },
  { id: 'number-04', number: '04', name: 'Cái ghế', imageUrl: '/number-images/04.webp', sortOrder: 4 },
  { id: 'number-05', number: '05', name: 'Quả táo', imageUrl: '/number-images/05.webp', sortOrder: 5 },
  { id: 'number-06', number: '06', name: 'Vỏ ốc', imageUrl: '/number-images/06.webp', sortOrder: 6 },
  { id: 'number-07', number: '07', name: 'Cái rìu', imageUrl: '/number-images/07.webp', sortOrder: 7 },
  { id: 'number-08', number: '08', name: 'Người tuyết', imageUrl: '/number-images/08.webp', sortOrder: 8 },
  { id: 'number-09', number: '09', name: 'Hươu cao cổ', imageUrl: '/number-images/09.webp', sortOrder: 9 },
  { id: 'number-10', number: '10', name: 'Con heo', imageUrl: '/number-images/10.webp', sortOrder: 10 },
  { id: 'number-11', number: '11', name: 'Cái thang', imageUrl: '/number-images/11.webp', sortOrder: 11 },
  { id: 'number-12', number: '12', name: 'Cá mập', imageUrl: '/number-images/12.webp', sortOrder: 12 },
  { id: 'number-13', number: '13', name: 'Con bướm', imageUrl: '/number-images/13.webp', sortOrder: 13 },
  { id: 'number-14', number: '14', name: 'Thuyền buồm', imageUrl: '/number-images/14.webp', sortOrder: 14 },
  { id: 'number-15', number: '15', name: 'Túi tiền', imageUrl: '/number-images/15.webp', sortOrder: 15 },
  { id: 'number-16', number: '16', name: 'Con ốc sên', imageUrl: '/number-images/16.webp', sortOrder: 16 },
  { id: 'number-17', number: '17', name: 'Nốt nhạc', imageUrl: '/number-images/17.webp', sortOrder: 17 },
  { id: 'number-18', number: '18', name: 'Đèn giao thông', imageUrl: '/number-images/18.webp', sortOrder: 18 },
  { id: 'number-19', number: '19', name: 'Con chó', imageUrl: '/number-images/19.webp', sortOrder: 19 },
  { id: 'number-20', number: '20', name: 'Quả bom', imageUrl: '/number-images/20.webp', sortOrder: 20 },
  { id: 'number-21', number: '21', name: 'Cây nến', imageUrl: '/number-images/21.webp', sortOrder: 21 },
  { id: 'number-22', number: '22', name: 'Thiên nga', imageUrl: '/number-images/22.webp', sortOrder: 22 },
  { id: 'number-23', number: '23', name: 'Con công', imageUrl: '/number-images/23.webp', sortOrder: 23 },
  { id: 'number-24', number: '24', name: 'Con sóc', imageUrl: '/number-images/24.webp', sortOrder: 24 },
  { id: 'number-25', number: '25', name: 'Cần cẩu', imageUrl: '/number-images/25.webp', sortOrder: 25 },
  { id: 'number-26', number: '26', name: 'Gà trống', imageUrl: '/number-images/26.webp', sortOrder: 26 },
  { id: 'number-27', number: '27', name: 'Con chuột', imageUrl: '/number-images/27.webp', sortOrder: 27 },
  { id: 'number-28', number: '28', name: 'Cà rốt và thỏ', imageUrl: '/number-images/28.webp', sortOrder: 28 },
  { id: 'number-29', number: '29', name: 'Chuột máy tính', imageUrl: '/number-images/29.webp', sortOrder: 29 },
  { id: 'number-30', number: '30', name: 'Núi và mặt trời', imageUrl: '/number-images/30.webp', sortOrder: 30 },
  { id: 'number-31', number: '31', name: 'Bóng đèn', imageUrl: '/number-images/31.webp', sortOrder: 31 },
  { id: 'number-32', number: '32', name: 'Vòi sen', imageUrl: '/number-images/32.webp', sortOrder: 32 },
  { id: 'number-33', number: '33', name: 'Cúc áo', imageUrl: '/number-images/33.webp', sortOrder: 33 },
  { id: 'number-34', number: '34', name: 'Kim cương', imageUrl: '/number-images/34.webp', sortOrder: 34 },
  { id: 'number-35', number: '35', name: 'Đu đủ', imageUrl: '/number-images/35.webp', sortOrder: 35 },
  { id: 'number-36', number: '36', name: 'Hoa hồng', imageUrl: '/number-images/36.webp', sortOrder: 36 },
  { id: 'number-37', number: '37', name: 'Loa cầm tay', imageUrl: '/number-images/37.webp', sortOrder: 37 },
  { id: 'number-38', number: '38', name: 'Nhẫn kim cương', imageUrl: '/number-images/38.webp', sortOrder: 38 },
  { id: 'number-39', number: '39', name: 'Tê giác', imageUrl: '/number-images/39.webp', sortOrder: 39 },
  { id: 'number-40', number: '40', name: 'Bút chì', imageUrl: '/number-images/40.webp', sortOrder: 40 },
  { id: 'number-41', number: '41', name: 'Bình cứu hỏa', imageUrl: '/number-images/41.webp', sortOrder: 41 },
  { id: 'number-42', number: '42', name: 'Cây diều', imageUrl: '/number-images/42.webp', sortOrder: 42 },
  { id: 'number-43', number: '43', name: 'Người lướt sóng', imageUrl: '/number-images/43.webp', sortOrder: 43 },
  { id: 'number-44', number: '44', name: 'Rừng thông', imageUrl: '/number-images/44.webp', sortOrder: 44 },
  { id: 'number-45', number: '45', name: 'Nam châm', imageUrl: '/number-images/45.webp', sortOrder: 45 },
  { id: 'number-46', number: '46', name: 'Cung tên', imageUrl: '/number-images/46.webp', sortOrder: 46 },
  { id: 'number-47', number: '47', name: 'Cầu thang', imageUrl: '/number-images/47.webp', sortOrder: 47 },
  { id: 'number-48', number: '48', name: 'Doremon', imageUrl: '/number-images/48.webp', sortOrder: 48 },
  { id: 'number-49', number: '49', name: 'Cái ly', imageUrl: '/number-images/49.webp', sortOrder: 49 },
  { id: 'number-50', number: '50', name: 'Xe đạp', imageUrl: '/number-images/50.webp', sortOrder: 50 },
  { id: 'number-51', number: '51', name: 'Sư tử', imageUrl: '/number-images/51.webp', sortOrder: 51 },
  { id: 'number-52', number: '52', name: 'Xe hơi', imageUrl: '/number-images/52.webp', sortOrder: 52 },
  { id: 'number-53', number: '53', name: 'Răng', imageUrl: '/number-images/53.webp', sortOrder: 53 },
  { id: 'number-54', number: '54', name: 'Người phục vụ', imageUrl: '/number-images/54.webp', sortOrder: 54 },
  { id: 'number-55', number: '55', name: 'Găng đấm bốc', imageUrl: '/number-images/55.webp', sortOrder: 55 },
  { id: 'number-56', number: '56', name: 'Phao cứu sinh', imageUrl: '/number-images/56.webp', sortOrder: 56 },
  { id: 'number-57', number: '57', name: 'Cổng thành', imageUrl: '/number-images/57.webp', sortOrder: 57 },
  { id: 'number-58', number: '58', name: 'Chú hề', imageUrl: '/number-images/58.webp', sortOrder: 58 },
  { id: 'number-59', number: '59', name: 'Con mèo', imageUrl: '/number-images/59.webp', sortOrder: 59 },
  { id: 'number-60', number: '60', name: 'Con cua', imageUrl: '/number-images/60.webp', sortOrder: 60 },
  { id: 'number-61', number: '61', name: 'Kẹo mút', imageUrl: '/number-images/61.webp', sortOrder: 61 },
  { id: 'number-62', number: '62', name: 'Điện thoại', imageUrl: '/number-images/62.webp', sortOrder: 62 },
  { id: 'number-63', number: '63', name: 'Xe máy', imageUrl: '/number-images/63.webp', sortOrder: 63 },
  { id: 'number-64', number: '64', name: 'Người lính', imageUrl: '/number-images/64.webp', sortOrder: 64 },
  { id: 'number-65', number: '65', name: 'Cú mèo', imageUrl: '/number-images/65.webp', sortOrder: 65 },
  { id: 'number-66', number: '66', name: 'Tai nghe', imageUrl: '/number-images/66.webp', sortOrder: 66 },
  { id: 'number-67', number: '67', name: 'Con cá', imageUrl: '/number-images/67.webp', sortOrder: 67 },
  { id: 'number-68', number: '68', name: 'Bình hoa', imageUrl: '/number-images/68.webp', sortOrder: 68 },
  { id: 'number-69', number: '69', name: 'Bát quái', imageUrl: '/number-images/69.webp', sortOrder: 69 },
  { id: 'number-70', number: '70', name: 'Sầu riêng', imageUrl: '/number-images/70.webp', sortOrder: 70 },
  { id: 'number-71', number: '71', name: 'Lá cờ', imageUrl: '/number-images/71.webp', sortOrder: 71 },
  { id: 'number-72', number: '72', name: 'Con ma', imageUrl: '/number-images/72.webp', sortOrder: 72 },
  { id: 'number-73', number: '73', name: 'Con trâu', imageUrl: '/number-images/73.webp', sortOrder: 73 },
  { id: 'number-74', number: '74', name: 'Con đường', imageUrl: '/number-images/74.webp', sortOrder: 74 },
  { id: 'number-75', number: '75', name: 'Xe tăng', imageUrl: '/number-images/75.webp', sortOrder: 75 },
  { id: 'number-76', number: '76', name: 'Nước mía', imageUrl: '/number-images/76.webp', sortOrder: 76 },
  { id: 'number-77', number: '77', name: 'Khẩu súng', imageUrl: '/number-images/77.webp', sortOrder: 77 },
  { id: 'number-78', number: '78', name: 'Cà chua', imageUrl: '/number-images/78.webp', sortOrder: 78 },
  { id: 'number-79', number: '79', name: 'Trái dừa', imageUrl: '/number-images/79.webp', sortOrder: 79 },
  { id: 'number-80', number: '80', name: 'Dấu chân', imageUrl: '/number-images/80.webp', sortOrder: 80 },
  { id: 'number-81', number: '81', name: 'Loa thùng', imageUrl: '/number-images/81.webp', sortOrder: 81 },
  { id: 'number-82', number: '82', name: 'Cá sấu', imageUrl: '/number-images/82.webp', sortOrder: 82 },
  { id: 'number-83', number: '83', name: 'Bạch tuộc', imageUrl: '/number-images/83.webp', sortOrder: 83 },
  { id: 'number-84', number: '84', name: 'Cây kéo', imageUrl: '/number-images/84.webp', sortOrder: 84 },
  { id: 'number-85', number: '85', name: 'Hạt đậu', imageUrl: '/number-images/85.webp', sortOrder: 85 },
  { id: 'number-86', number: '86', name: 'Chùm nho', imageUrl: '/number-images/86.webp', sortOrder: 86 },
  { id: 'number-87', number: '87', name: 'Kính thiên văn', imageUrl: '/number-images/87.webp', sortOrder: 87 },
  { id: 'number-88', number: '88', name: 'Còng tay', imageUrl: '/number-images/88.webp', sortOrder: 88 },
  { id: 'number-89', number: '89', name: 'Thuốc nổ', imageUrl: '/number-images/89.webp', sortOrder: 89 },
  { id: 'number-90', number: '90', name: 'Dao và thớt', imageUrl: '/number-images/90.webp', sortOrder: 90 },
  { id: 'number-91', number: '91', name: 'Sóng biển', imageUrl: '/number-images/91.webp', sortOrder: 91 },
  { id: 'number-92', number: '92', name: 'Bóng bay', imageUrl: '/number-images/92.webp', sortOrder: 92 },
  { id: 'number-93', number: '93', name: 'Cúp vàng', imageUrl: '/number-images/93.webp', sortOrder: 93 },
  { id: 'number-94', number: '94', name: 'Gốc cây', imageUrl: '/number-images/94.webp', sortOrder: 94 },
  { id: 'number-95', number: '95', name: 'Bác sĩ', imageUrl: '/number-images/95.webp', sortOrder: 95 },
  { id: 'number-96', number: '96', name: 'Cái trống', imageUrl: '/number-images/96.webp', sortOrder: 96 },
  { id: 'number-97', number: '97', name: 'Con dê', imageUrl: '/number-images/97.webp', sortOrder: 97 },
  { id: 'number-98', number: '98', name: 'Con ong', imageUrl: '/number-images/98.webp', sortOrder: 98 },
  { id: 'number-99', number: '99', name: 'Vợt cầu lông', imageUrl: '/number-images/99.webp', sortOrder: 99 },
];
